### ISSUE TITLE
Can you delete my Issue? It was my mistake, it was the wrong Repo, sry

### ISSUE THREAD

**Issue by sebcodes** [tigerabrodi/Grand-Burger#1]

**Comment by sebcodes** [comment]
Can you delete my Issue? It was my mistake, it was the wrong Repo, sry

**Comment by tigerabrodi** [comment]
its closed

**Comment by sebcodes** [comment]
Ok thank you, can you delete this issue please?

Von: Tiger Abrodi <notifications@github.com> 
Gesendet: Dienstag, 20. Oktober 2020 13:59
An: tigerabrodi/Grand-Burger <Grand-Burger@noreply.github.com>
Cc: Sebastian Kiefer <info@sebastian-kiefer.com>; State change <state_change@noreply.github.com>
Betreff: Re: [tigerabrodi/Grand-Burger] Can you delete my Issue? It was my mistake, it was the wrong Repo, sry (#1)

 

its closed
